### ISSUE TITLE
src=path/to/image should be :src=path/to/image

### ISSUE THREAD

**Issue by jyjunyz** [vue-comps/vue-parallax#1]
when I use this method, the image request contentType always is text/html, then i modified the method like this:
< parallax :src=src >
and in the script:
  data () {
            return {
                src: require('../assets/night-view.jpg')
            }
        }
this component can work successfully. (my project is generated by vue-cli, and Integrated vue-loader, maybe this causes the difference)

**Comment by paulpflug** [comment]
I do not fully understand. When exactly the contentType is text/html?

I will look into it..

**Comment by paulpflug** [comment]
I think I understand now. A problem when your assets are organized by webpack.

This should also work:

``` html
<parallax src=require('../assets/night-view.jpg')>
```
