### ISSUE TITLE
Support Vue 2.0 

### ISSUE THREAD

**Issue by bepsvpt** [vue-comps/vue-parallax#2]
v-el and v-ref are deprecated in Vue 2.0, any plan to support Vue 2.0 ?

**Comment by paulpflug** [comment]
now it supports 2.0 :+1:

**Comment by bepsvpt** [comment]
Thanks :)

**Comment by yazfield** [comment]
how do I get the  Vue 2.0 version? `npm install --save-dev vue-parallax` is linked to v1
