### ISSUE TITLE
Demo page looks twitching

### ISSUE THREAD

**Issue by sobolevn** [vue-comps/vue-parallax#3]
First of all, thanks for your component!

When surfing the net in the desperate search for some ready `vue-parallax` component I came across your library. 

I know that 'twitching' is not a technical term, but I can't describe that behavior in other words. Just compare: http://pixelcog.github.io/parallax.js/ and your demo.

Here are my stats about memory usage:
<img width="370" alt="2016-10-17 22 04 16" src="https://cloud.githubusercontent.com/assets/4660275/19451368/b1abb236-94b5-11e6-9088-2e1772a69156.png">

I guess 468 MB is a huge amount of memory just for two images.

Or maybe I have some bugs with my specific setup? I am using:
- latest Chrome
- macOS X

**Comment by paulpflug** [comment]
you are right.
here https://github.com/vue-comps/vue-parallax/blob/master/src/parallax.vue#L47 I'm rounding to much, probably one reason for twitching.

But most imporantly I did something wrong with the calculations .. 

I will look into it

**Comment by sobolevn** [comment]
Thanks for the quick fix! Much better now!
