### ISSUE TITLE
CAnt import in laravel 5.3

### ISSUE THREAD

**Issue by elib0** [vue-comps/vue-parallax#4]
Registring in app.js
`Vue.component('parallax', require('vue-parallax'));`

console massage
`VM2327:1 Uncaught Error: Module build failed: SyntaxError: 'with' in strict mode`

**Comment by paulpflug** [comment]
hey,
please read https://github.com/vue-comps/vue-icons/issues/4

looks like laravel is using rollup which tries to process `parallax.js` with some sort of ES6 processor, which enforces `strict` mode.

Could you try to exclude vue-parallax from getting processed?

**Comment by elib0** [comment]
whoo thank you for your quick response Paul, I will try to exclude vue-parralax, thk again

**Comment by paulpflug** [comment]
I'm not using rollup, could you explain how to exclude the file from processing? then I will put it in the readme.
