### ISSUE TITLE
Bugs V1

### ISSUE THREAD

**Issue by elib0** [vue-comps/vue-parallax#5]
Hi again, :)

You can apply the corrections version 2 to version 1?

Version 1 in mobile not work :(

**Comment by paulpflug** [comment]
ok, try 1.1.0

**Comment by elib0** [comment]
whoo you are very fast, but still does not work with mobile, background-position: top/bottom they have no effect when scrolling

**Comment by elib0** [comment]
now it does't work in desktops :(

**Comment by paulpflug** [comment]
could you be a bit more specific? what exactly isn't working?

**Comment by elib0** [comment]
-background motion, in V1.0.0 the bg image changed its position in Y according to the scroll

and mobile is still seen bad, background repeat in Y ?

![mobile](https://cloud.githubusercontent.com/assets/1808713/19770257/fed92e0e-9c34-11e6-9af6-3789909d49e3.JPG)

**Comment by paulpflug** [comment]
which speed are you using? try 0.2

could you try v1.1.1? I had a bug with offset..

**Comment by elib0** [comment]
work fine in speed 0.2 :D thanks, in mobile  still seen bad but scroll work fine

eg: same image last comment
