### ISSUE TITLE
[Vue warn]: "style" is a reserved attribute and cannot be used as component prop. 

### ISSUE THREAD

**Issue by adsellor** [vue-comps/vue-parallax#7]
Hey there,
I'm trying to use vue-parallax with nuxt.js but get ``` [Vue warn]: "style" is a reserved attribute and cannot be used as component prop. ``` error. I tried to change the prop manually in a fork and open PR but get the same error anyway.
Maybe you could help,
Thanks in advance

**Comment by j2pb** [comment]
same issue here!

**Comment by SkyooAdmin** [comment]
I'm having the same issue.

**Comment by gifteddiz** [comment]
+1
Any solutions?
